### ISSUE TITLE
generic test group/parameter for tests.aws/gce/azure ?

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch-parent#41]
Or, alternatively change these builds to use -Dtests.filter to specify test groups? 

Either way, I think if we take care of this, aws/gce/azure plugins don't need custom mvn test logic and can just re-use elasticearch-parent logic.

**Comment by dadoonet** [comment]
I agree to have a generic group which basically needs to be set to run integration tests 

That would have a lot of benefits !

**Comment by dadoonet** [comment]
Something like -Dtests.3rdparty=true ?

**Comment by rmuir** [comment]
I have been trying to think of a name too. basically to me for this test group, the idea is that the test requires some custom configuration/credentials to be supplied (via tests.config) by the user in order to work.

**Comment by rmuir** [comment]
I got nothing better than 3rdparty. except i'd prefer `tests.thirdparty` and `@ThirdParty` just in case anything cares about the name being an identifier (vs starting with a digit).

I will take a stab.

**Comment by dadoonet** [comment]
+1 for alphabetics only

**Comment by rmuir** [comment]
Here is my prototype to add to es-core's test framework:

    /**
     * Property that controls whether ThirdParty Integration tests are run (not the default).
     */
    public static final String SYSPROP_THIRDPARTY = "tests.thirdparty";
    
    /**
     * Annotation for third-party integration tests.
     * <p>
     * These are tests the require a third-party service in order to run. They
     * may require the user to manually configure a service (such as rabbitmq)
     * and may additionally require some external configuration (e.g. AWS credentials) 
     * via the {@code tests.config} system property.
     */
    @Inherited
    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.TYPE)
    @TestGroup(enabled = false, sysProperty = ElasticsearchIntegrationTest.SYSPROP_THIRDPARTY)
    public @interface ThirdParty {
    }


I will mvn install locally and see if i can get it working for various plugins, and open an ES PR if it all works out.

**Comment by rmuir** [comment]
I applied this to all plugin builds and opened an issue to pass the new parameter in CI.

No more duplicate junit test configurations! just es-parent and es-core now :)

**Comment by dadoonet** [comment]
w00t! Fantastic!

**Comment by dadoonet** [comment]
Can you backport it to 1.x branch as well (So in es-1.x plugins branches)?

**Comment by rmuir** [comment]
It might not be so easy considering test-framework overhaul was in master-only. So lots of parameters changed here, even simple ones like ifNoTests only apply to master. I think test framework version may also be newer. In general for all changes, currently I put 100% of my efforts into master branch only at this point. It is a tradeoff, but I think the right one.

**Comment by dadoonet** [comment]
Makes sense to me. We can leave with that :)
