### ISSUE TITLE
[maven] fix warnings

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch-parent#46]
Some warnings appear in IntelliJ for the parent project:

The following variables are unknown. We should probably set them as properties. Note that every sub plugin or any user can overload those properties when running maven:

* `${project.parent.build.directory}` (if #45 is merged)
* `${java.permGenSpace}`
* `${forbidden.signatures}`
* `${forbidden.test.signatures}`
* `${scmBranch}`
* `${validate.skip}`
* `${validate.patternsFound}`
* `${skipTests}`
* `${plugin_classpath}`
* `${runtime_classpath}`
* `${test_classpath}`

Also, it sounds like this plugin can not be found:

```xml
                <dependency>
                    <!--  must be on the classpath  -->
                    <groupId>org.jacoco</groupId>
                    <artifactId>org.jacoco.agent</artifactId>
                    <classifier>runtime</classifier>
                    <scope>test</scope>
                </dependency>
```

**Comment by rmuir** [comment]
> Also, it sounds like this plugin can not be found:

There is nothing wrong with jacoco, its both declared in dependencyManagement, and works (if i do a jacoco profiling build of say kuromoji: mvn -Dtests.coverage=true test jacoco:report, then it produces target/site/jacoco with coverage report).

**Comment by dadoonet** [comment]
Yeah. Just that IntelliJ adds a warning on this part. Might be an issue in IntelliJ?
