### ISSUE TITLE
[maven] move elasticsearch-plugin pom artifact to o.e.plugin groupId

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch-parent#47]
I think we should move from:

```xml
<parent>
    <groupId>org.elasticsearch</groupId>
    <artifactId>elasticsearch-plugin</artifactId>
    <version>2.0.0-SNAPSHOT</version>
</parent>
```

to 

```xml
<parent>
    <groupId>org.elasticsearch.plugin</groupId>
    <artifactId>elasticsearch-plugin</artifactId>
    <version>2.0.0-SNAPSHOT</version>
</parent>
```

So plugins we produce then will use also the same groupId. For example, we could move kuromoji to:

```xml
<groupId>org.elasticsearch.plugin</groupId>
<artifactId>elasticsearch-analysis-kuromoji</artifactId>
<version>2.0.0-SNAPSHOT</version>
```

(instead of `3.0.0-SNAPSHOT`) BTW.

@rmuir WDYT?

**Comment by rmuir** [comment]
if it prevents any confusion from pluginmanager, this seems like a good solution to me. then we don't have to rename all artifacts.

**Comment by dadoonet** [comment]
@rmuir It won't solve the plugin manager issue as the plugin manager don't rely on the groupId.
Unless we download using `groupId/artifactId/version` notation which will download from maven central.

We can imagine different solutions about this but to me it's outside of the scope of this issue.

* Add a first download repository (before the current download service we have) which will try first to download the plugin from `http://download.elasticsearch.org/elasticsearch/plugins/pluginname/version` instead of `http://download.elasticsearch.org/elasticsearch/pluginname/pluginname-version/`. It will be super easy to add once @tlrx will have merged his pending PR about the plugin manager refactoring.
* Ask users to now download a plugin by asking the groupId (default to org.elasticsearch.plugin). Then use this groupId as a dir name when downloading from our download service
* Use a maven repository service like `maven.elastic.co` or similar to simply upload our artifacts only once in it and then sync the public content to maven central. Today when we release, we upload to both sonatype AND the download service.

But as I said, I think it should be another discussion than this thread.

**Comment by dadoonet** [comment]
I thought again about it. Actually, there is not really need to change the plugin manager but just to change the documentation and the release scripts.
If we consider that we now upload whatever plugin to S3 `download.elasticsearch.org` bucket in `groupId/name/name-version` instead of `elasticsearch/name/name-version`, we just have to tell people to use `bin/plugin install groupId/name/version` and this should work out of the box.

But of course, we could simplify this in the plugin manager as well.
