### ISSUE TITLE
Update to Elasticsearch 2.0.0

### ISSUE THREAD

**Issue by emig** [elastic/elasticsearch-parent#55]

**Comment by dadoonet** [comment]
Since 2.0, this project is not used anymore as everything moved to elasticsearch repository.

Have a look at https://github.com/elastic/elasticsearch/blob/2.0/pom.xml

You could depend on:

``` xml
<groupId>org.elasticsearch</groupId>
<artifactId>parent</artifactId>
<version>2.0.1</version>
```

Or on [plugins](https://github.com/elastic/elasticsearch/blob/2.0/plugins/pom.xml):

``` xml
<groupId>org.elasticsearch.plugin</groupId>
<artifactId>plugins</artifactId>
<version>2.0.1</version>
```

**Comment by emig** [comment]
@dadoonet thanks for the information.
